[project]
name = "jobSched"
version = "0.1.0"
description = "Parallel job scheduler"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
